### ISSUE TITLE
configure for market making

### ISSUE THREAD

**Issue by andristarr** [purefinance/mmb#159]
How is this configured for market making? If I am correct glancing through the code this is a trading engine as you highlight it, but it lacks the market making logic itself.

**Comment by siberianguy** [comment]
The current strategy is very basic and you can find it over here: https://github.com/purefinance/mmb/tree/main/example/src/strategies

We're at the end of the milestone, so we're in the process of polishing the code and docs, so it's more usable for people outside the core team
