### ISSUE TITLE
What is the benefit of having two channels for main and secondary for WS?

### ISSUE THREAD

**Issue by FreerGit** [purefinance/mmb#346]
As title states, trying to understand why websocket has two different channels (/core/src/connectivity/websocket.rs)

```Rust

pub struct WsSender {
    /// Main websocket connection sender
    main_sender: mpsc::UnboundedSender<Message>,
    /// Secondary websocket connection sender
    secondary_sender: Option<mpsc::UnboundedSender<Message>>,
    /// Cancellation token for service futures
    _cancel: CancellationTokenDropGuard,
}
````
Is one for hotpath data such as trades/orderbook updates and the secondary one for intra service communication, trigger callback etc?

**Comment by siberianguy** [comment]
Some exchanges (i. e. Binance) have separate Web Socket endpoints for private and public notifications
